<a href="https://colab.research.google.com/github/ayushikhandelwal99/ML/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy


In [0]:
import numpy as np

In [0]:
a=np.array([2,7,1,99])

In [0]:
type(a)

numpy.ndarray

In [0]:
b=np.array([12,17,11,199,14])

In [0]:
a

array([ 2,  7,  1, 99])

In [0]:
b

array([ 12,  17,  11, 199,  14])

In [0]:
a[0]

2

In [0]:
a=np.array([2,7,1,99,4])

In [0]:
a+b

array([ 14,  24,  12, 298,  18])

In [0]:
a+2


array([  4,   9,   3, 101,   6])

In [0]:
a*2

array([  4,  14,   2, 198,   8])

In [0]:
a**2

array([   4,   49,    1, 9801,   16])

In [0]:
a*b

array([   24,   119,    11, 19701,    56])

In [0]:
b/a

array([ 6.        ,  2.42857143, 11.        ,  2.01010101,  3.5       ])

In [0]:
b**a


array([                 144,            410338673,                   11,
       -8280573923978350953,                38416])

In [0]:
b**a

array([                 144,            410338673,                   11,
       -8280573923978350953,                38416])

In [0]:
c=np.array([[2,5,8],[2,6,4],[7,9,3]])

In [0]:
c

array([[2, 5, 8],
       [2, 6, 4],
       [7, 9, 3]])

In [0]:
c[0][2]

8

In [0]:
c[2]

array([7, 9, 3])

In [0]:
c+4

array([[ 6,  9, 12],
       [ 6, 10,  8],
       [11, 13,  7]])

In [0]:
print(c-2)
print(c*2)
print(c**2)

[[0 3 6]
 [0 4 2]
 [5 7 1]]
[[ 4 10 16]
 [ 4 12  8]
 [14 18  6]]
[[ 4 25 64]
 [ 4 36 16]
 [49 81  9]]


In [0]:
import numpy as np


In [6]:
d=np.arange(20).reshape(4,5)
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
np.arange(20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
np.ones((4,4,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [23]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.random((3,3)) #taking any rendom element of array

array([[0.31668659, 0.0543347 , 0.39123606],
       [0.45894429, 0.1959095 , 0.84573321],
       [0.99443171, 0.39836827, 0.56052043]])

In [27]:
a1=np.array([[2,3],[5,4]])
a1

array([[2, 3],
       [5, 4]])

In [29]:
b1=np.array([[1,2],[3,4]])
b1

array([[1, 2],
       [3, 4]])

In [30]:
np.add(a1,b1)

array([[3, 5],
       [8, 8]])

In [33]:
np.subtract(a1,b1)

array([[1, 1],
       [2, 0]])

In [35]:
np.multiply(a1,b1)

array([[ 2,  6],
       [15, 16]])

In [37]:
np.sqrt(a1)

array([[1.41421356, 1.73205081],
       [2.23606798, 2.        ]])

In [38]:
np.divide(a1,2)

array([[1. , 1.5],
       [2.5, 2. ]])

In [41]:
np.arange(10)**2  #making square of array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])