<a href="https://colab.research.google.com/github/ayushikhandelwal99/ML/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy


In [0]:
import numpy as np

In [0]:
a=np.array([2,7,1,99])

In [0]:
type(a)

numpy.ndarray

In [0]:
b=np.array([12,17,11,199,14])

In [0]:
a

array([ 2,  7,  1, 99])

In [0]:
b

array([ 12,  17,  11, 199,  14])

In [0]:
a[0]

2

In [0]:
a=np.array([2,7,1,99,4])

In [0]:
a+b

array([ 14,  24,  12, 298,  18])

In [0]:
a+2


array([  4,   9,   3, 101,   6])

In [0]:
a*2

array([  4,  14,   2, 198,   8])

In [0]:
a**2

array([   4,   49,    1, 9801,   16])

In [0]:
a*b

array([   24,   119,    11, 19701,    56])

In [0]:
b/a

array([ 6.        ,  2.42857143, 11.        ,  2.01010101,  3.5       ])

In [0]:
b**a


array([                 144,            410338673,                   11,
       -8280573923978350953,                38416])

In [0]:
b**a

array([                 144,            410338673,                   11,
       -8280573923978350953,                38416])

In [0]:
c=np.array([[2,5,8],[2,6,4],[7,9,3]])

In [0]:
c

array([[2, 5, 8],
       [2, 6, 4],
       [7, 9, 3]])

In [0]:
c[0][2]

8

In [0]:
c[2]

array([7, 9, 3])

In [0]:
c+4

array([[ 6,  9, 12],
       [ 6, 10,  8],
       [11, 13,  7]])

In [0]:
print(c-2)
print(c*2)
print(c**2)

[[0 3 6]
 [0 4 2]
 [5 7 1]]
[[ 4 10 16]
 [ 4 12  8]
 [14 18  6]]
[[ 4 25 64]
 [ 4 36 16]
 [49 81  9]]
