<a href="https://colab.research.google.com/github/ayushikhandelwal99/ML/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy


In [0]:
import numpy as np

In [0]:
a=np.array([2,7,1,99])

In [0]:
type(a)

numpy.ndarray

In [0]:
b=np.array([12,17,11,199,14])

In [0]:
a

array([ 2,  7,  1, 99])

In [0]:
b

array([ 12,  17,  11, 199,  14])

In [0]:
a[0]

2

In [0]:
a=np.array([2,7,1,99,4])

In [0]:
a+b

array([ 14,  24,  12, 298,  18])

In [0]:
a+2


array([  4,   9,   3, 101,   6])

In [0]:
a*2

array([  4,  14,   2, 198,   8])

In [0]:
a**2

array([   4,   49,    1, 9801,   16])

In [0]:
a*b

array([   24,   119,    11, 19701,    56])

In [0]:
b/a

array([ 6.        ,  2.42857143, 11.        ,  2.01010101,  3.5       ])

In [0]:
b**a


array([                 144,            410338673,                   11,
       -8280573923978350953,                38416])

In [0]:
b**a

array([                 144,            410338673,                   11,
       -8280573923978350953,                38416])

In [0]:
c=np.array([[2,5,8],[2,6,4],[7,9,3]])

In [0]:
c

array([[2, 5, 8],
       [2, 6, 4],
       [7, 9, 3]])

In [0]:
c[0][2]

8

In [0]:
c[2]

array([7, 9, 3])

In [0]:
c+4

array([[ 6,  9, 12],
       [ 6, 10,  8],
       [11, 13,  7]])

In [0]:
print(c-2)
print(c*2)
print(c**2)

[[0 3 6]
 [0 4 2]
 [5 7 1]]
[[ 4 10 16]
 [ 4 12  8]
 [14 18  6]]
[[ 4 25 64]
 [ 4 36 16]
 [49 81  9]]


In [0]:
import numpy as np


In [6]:
d=np.arange(20).reshape(4,5)
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
np.arange(20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
np.ones((4,4,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [23]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.random((3,3)) #taking any rendom element of array

array([[0.31668659, 0.0543347 , 0.39123606],
       [0.45894429, 0.1959095 , 0.84573321],
       [0.99443171, 0.39836827, 0.56052043]])

In [27]:
a1=np.array([[2,3],[5,4]])
a1

array([[2, 3],
       [5, 4]])

In [29]:
b1=np.array([[1,2],[3,4]])
b1

array([[1, 2],
       [3, 4]])

In [30]:
np.add(a1,b1)

array([[3, 5],
       [8, 8]])

In [33]:
np.subtract(a1,b1)

array([[1, 1],
       [2, 0]])

In [35]:
np.multiply(a1,b1)

array([[ 2,  6],
       [15, 16]])

In [37]:
np.sqrt(a1)

array([[1.41421356, 1.73205081],
       [2.23606798, 2.        ]])

In [38]:
np.divide(a1,2)

array([[1. , 1.5],
       [2.5, 2. ]])

In [41]:
np.arange(10)**2  #making square of array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [48]:
d=np.concatenate([a1,b1])
d

array([[2, 3],
       [5, 4],
       [1, 2],
       [3, 4]])

In [45]:
np.linspace(0,2,4) # create an array with four equally spaced points starting with 0 and ending with 2.

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [49]:
np.sin(d)

array([[ 0.90929743,  0.14112001],
       [-0.95892427, -0.7568025 ],
       [ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [50]:
np.cos(d)

array([[-0.41614684, -0.9899925 ],
       [ 0.28366219, -0.65364362],
       [ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [51]:
np.linspace(-np.pi,np.pi,100)

array([-3.14159265, -3.07812614, -3.01465962, -2.9511931 , -2.88772658,
       -2.82426006, -2.76079354, -2.69732703, -2.63386051, -2.57039399,
       -2.50692747, -2.44346095, -2.37999443, -2.31652792, -2.2530614 ,
       -2.18959488, -2.12612836, -2.06266184, -1.99919533, -1.93572881,
       -1.87226229, -1.80879577, -1.74532925, -1.68186273, -1.61839622,
       -1.5549297 , -1.49146318, -1.42799666, -1.36453014, -1.30106362,
       -1.23759711, -1.17413059, -1.11066407, -1.04719755, -0.98373103,
       -0.92026451, -0.856798  , -0.79333148, -0.72986496, -0.66639844,
       -0.60293192, -0.53946541, -0.47599889, -0.41253237, -0.34906585,
       -0.28559933, -0.22213281, -0.1586663 , -0.09519978, -0.03173326,
        0.03173326,  0.09519978,  0.1586663 ,  0.22213281,  0.28559933,
        0.34906585,  0.41253237,  0.47599889,  0.53946541,  0.60293192,
        0.66639844,  0.72986496,  0.79333148,  0.856798  ,  0.92026451,
        0.98373103,  1.04719755,  1.11066407,  1.17413059,  1.23

In [52]:
np.pi

3.141592653589793

In [0]:
from numpy.random import rand

In [0]:
from numpy.linalg import solve, inv

In [57]:
d

array([[2, 3],
       [5, 4],
       [1, 2],
       [3, 4]])

In [0]:
a = np.array([[1, 2, 3], [3, 4, 6.7], [5, 9.0, 5]])

In [60]:
inv(a)

array([[-2.27683616,  0.96045198,  0.07909605],
       [ 1.04519774, -0.56497175,  0.1299435 ],
       [ 0.39548023,  0.05649718, -0.11299435]])