<a href="https://colab.research.google.com/github/ayushikhandelwal99/ML/blob/master/punumber%3A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [10]:
l=int(input("no.of rows for a: "))
m=int(input("no.of columns for a:  "))
n=int(input("no. of rows for b: "))
o=int(input("no.of columns for b: "))

no.of rows for a: 3
no.of columns for a:  2
no. of rows for b: 2
no.of columns for b: 5


In [12]:
a=np.random.random((l,m))
a

array([[0.53653566, 0.2276211 ],
       [0.83311468, 0.69589399],
       [0.23138995, 0.74831915]])

In [13]:
b=np.random.random((n,o))
b

array([[0.34831209, 0.95199564, 0.16241319, 0.17121548, 0.18717174],
       [0.09449153, 0.52514309, 0.69055512, 0.05105234, 0.63286615]])

In [0]:
np.savetxt('a.txt',a)
x=np.loadtxt('a.txt')
np.savetxt('b.txt',b)
y=np.loadtxt('b.txt')

In [15]:
y

array([[0.34831209, 0.95199564, 0.16241319, 0.17121548, 0.18717174],
       [0.09449153, 0.52514309, 0.69055512, 0.05105234, 0.63286615]])

In [16]:
x

array([[0.53653566, 0.2276211 ],
       [0.83311468, 0.69589399],
       [0.23138995, 0.74831915]])