<a href="https://colab.research.google.com/github/ayushikhandelwal99/ML/blob/master/TASK2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
a=np.random.random((3,2))

In [3]:
a

array([[0.59002721, 0.23404051],
       [0.38172752, 0.40528119],
       [0.10529714, 0.75574346]])

In [4]:
b=np.random.random((2,5))
b

array([[0.53034414, 0.50979492, 0.16991236, 0.63082118, 0.59489263],
       [0.29430514, 0.10862119, 0.37367654, 0.44236611, 0.04070749]])

In [0]:
np.savetxt('a.txt',a)
x=np.loadtxt('a.txt')
np.savetxt('b.txt',b)
y=np.loadtxt('b.txt')

In [10]:
y

array([[0.53034414, 0.50979492, 0.16991236, 0.63082118, 0.59489263],
       [0.29430514, 0.10862119, 0.37367654, 0.44236611, 0.04070749]])

In [11]:
x

array([[0.59002721, 0.23404051],
       [0.38172752, 0.40528119],
       [0.10529714, 0.75574346]])